run_id: apple-tv-demo
video:
  sample_fps: 5.0
telemetry:
  adapter: s3
  s3_bucket: my-telemetry-bucket
  s3_prefix: path/to/events/
  s3_region: us-west-2
# Apple TV uses different IR codes and can be controlled via HomeKit or IP-based APIs
ir_blaster_host: 192.168.1.60
ir_blaster_type: custom
ir_device_id: apple-tv-1
