run_id: lg-demo
video:
  sample_fps: 5.0
telemetry:
  adapter: s3
  s3_bucket: my-telemetry-bucket
  s3_prefix: path/to/events/
  s3_region: us-west-2
# LG WebOS TVs can be controlled via HDMI CEC or LG's native IR codes
ir_blaster_host: 192.168.1.62
ir_blaster_type: custom
ir_device_id: lg-webos-1
